server {
  listen 80;
  server_name _;

  location = /health {
    access_log off;
    return 200 "ok\n";
  }

  location = / {
    return 302 https://home.xn--pcwchter-2za.de/;
  }

  location = /login {
    return 302 https://home.xn--pcwchter-2za.de/;
  }

  location = /home {
    return 302 https://home.xn--pcwchter-2za.de/;
  }

  location = /console {
    return 302 https://console.xn--pcwchter-2za.de/;
  }

  location = /admin {
    return 302 https://console.xn--pcwchter-2za.de/;
  }

  location / {
    proxy_pass http://keycloak:8080;
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Port 443;

    proxy_read_timeout 600s;
  }
}
